language: haskell
install:
    - cabal install --only-dependencies --enable-tests --enable-benchmarks
    - cabal configure --enable-tests --enable-benchmarks
    - cabal build
    - cabal haddock
    - cabal test --show-details=always
    - cabal bench
