language: haskell
install:
    - cabal install criterion
    - cabal install test-framework
    - cabal install test-framework-quickcheck2
    - cabal configure --enable-tests --enable-benchmarks
    - cabal build
    - cabal haddock
    - cabal test --show-details=always
    - cabal bench
